services:
  postgres:
    image: postgres:15
    env_file:
      - ./api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    container_name: minio
    env_file:
      - ./api/.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]

  temporal:
    image: temporalio/auto-setup:1.27.2
    container_name: temporal
    ports:
      - "7233:7233"
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PWD: password
      POSTGRES_SEEDS: postgres
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      ENABLE_ES: false
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./worker/dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.27.2-tctl-1.18.2-cli-1.3.0
    stdin_open: true
    tty: true

  temporal-ui:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.34.0
    ports:
      - 8080:8080

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/dbname
      TEMPORAL_SERVICE: temporal:7233
    depends_on:
      minio:
        condition: service_started
      postgres:
        condition: service_healthy
      temporal:
        condition: service_started

  worker:
    build:
      context: ./worker
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@postgres:5432/dbname
      TEMPORAL_SERVICE: temporal:7233
    depends_on:
      postgres:
        condition: service_healthy
      temporal:
        condition: service_started
      minio:
        condition: service_started

volumes:
  postgres_data:
  minio_data:
