FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml .

RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root
RUN pip install pathlib transformers peft
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
RUN transformers-cli download openai/whisper-small
RUN pip install soundfile

COPY whisper-small-lora-ru .

COPY . .

CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003"]
