name: Worker CI

on:
  push:
    paths:
      - 'worker/**'
  pull_request:
    paths:
      - 'worker/**'

env:
  POETRY_VERSION: '1.6.1'
  PYTHON_VERSION: '3.12'

  SQL_HOST: ${{ secrets.WORKER_SQL_HOST }}
  SQL_PORT: ${{ secrets.WORKER_SQL_PORT }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==${{ env.POETRY_VERSION }}

      - name: Install dependencies
        working-directory: worker
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run flake8
        working-directory: worker
        run: |
          poetry run flake8 .

  lint-ruff:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==${{ env.POETRY_VERSION }}

      - name: Install dependencies
        working-directory: worker
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run ruff
        working-directory: worker
        run: |
          poetry run ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint-ruff
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==${{ env.POETRY_VERSION }}

      - name: Install dependencies
        working-directory: worker
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run pytest
        working-directory: worker
        run: |
          poetry run pytest

  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          docker build \
            --build-arg SQL_HOST=${{ env.SQL_HOST }} \
            --build-arg SQL_PORT=${{ env.SQL_PORT }} \
            -t ghcr.io/${{ github.repository_owner }}/worker:${{ github.sha }} \
            -f worker/Dockerfile worker
          docker push ghcr.io/${{ github.repository_owner }}/worker:${{ github.sha }}
